image: geoffreybooth/meteor-base

stages:
  - build
  - deploy

cache:
  key: node-packages
  paths:
    - node_modules


install-dependencies:
  stage: .pre
  script:
    - meteor npm install

build-job:
  stage: build
  script:
    - meteor build --architecture os.linux.x86_64 --directory ./build
  artifacts:
    paths:
      - build/
build-docker:
  image: docker:latest
  stage: build
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy-prod:
  stage: deploy
  only:
    - master
  dependencies:
    - build-job
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
